version: '3.5'

services:

  ipfs-ethereum:
    container_name: ipfs-ethereum
    build: ./../../decentralized-storage
    expose:
      - 5001
    ports:
      - 5001:5001
    networks:
      - anyledger-net

  lwm2m-server-ethereum:
    container_name: lwm2m-server-ethereum
    restart: on-failure
    depends_on:
      - ipfs-ethereum
    build: ./../../leshan/leshan-server-cluster-ipfs
    expose:
      - 5001
      - 5683
      - 5684
      - 5783
      - 5784
      - 8081
    links:
      - ipfs-ethereum
      - ganache-cli
    networks:
      - anyledger-net

  ganache-cli:
    container_name: ganache-cli
    image: trufflesuite/ganache-cli:v6.1.0
    command: ["-d", "-p", "8545", "--account", "0x76dda3572973659eabbd6c9279b66256838038da8189ee689e174e7acabfe3c5,1000000000000000000000000"]
    expose:
      - 8545
    ports:
      - 127.0.0.1:8545:8545
    networks:
      - anyledger-net

  anyledger-hub-ethereum:
    container_name: anyledger-hub-ethereum
    build: ./../../anyledger-hub-web
    expose:
      - 4001
      - 4002
      - 8080
    ports:
      - 4001:4001
      - 4002:4002/udp
      - 8080:8080
    networks:
      - anyledger-net

  truffle:
    container_name: truffle
    build: ./../../smart-contracts/ethereum
    depends_on:
      - ganache-cli
    links:
      - ganache-cli
    networks:
      - anyledger-net

  lwm2m-client_1-ethereum:
    container_name: lwm2m-client_1-ethereum
    restart: on-failure
    depends_on:
      - lwm2m-server-ethereum
      - truffle
    build: ./../../leshan/leshan-client-demo
    links:
      - lwm2m-server-ethereum
    networks:
      - anyledger-net

  lwm2m-client_2-ethereum:
    container_name: lwm2m-client_2-ethereum
    restart: on-failure
    depends_on:
      - lwm2m-server-ethereum
      - truffle
    build: ./../../leshan/leshan-client-demo
    links:
      - lwm2m-server-ethereum
    networks:
      - anyledger-net

  lwm2m-client_3-ethereum:
    container_name: lwm2m-client_3-ethereum
    restart: on-failure
    depends_on:
      - lwm2m-server-ethereum
      - truffle
    build: ./../../leshan/leshan-client-demo
    links:
      - lwm2m-server-ethereum
    networks:
      - anyledger-net

networks:
  anyledger-net:
    driver: bridge
